version: '3.1'
services:
  toyas:
    build: .
    ports:
      - "80:5000"
    volumes:
      - .:/app
  
  demo_client:
    build: ./demo_client
    ports:
      - "5000:5000"
    volumes:
      - ./demo_client:/app
    depends_on:
      - toyas

networks:
  default:
      name: toyas_default
